/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Jhon
 */
public class ForMenu extends javax.swing.JFrame {

    /**
     * Creates new form ForMenu
     */
    public ForMenu() {
        initComponents();
        AreaCentral.setBackground(new java.awt.Color(52,52,52,235)); //Transparecia en el jPanel
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        nombreEmpresa = new javax.swing.JLabel();
        AreaCentral = new javax.swing.JPanel();
        PanelEmpleado = new javax.swing.JPanel();
        textoEmpleado = new javax.swing.JLabel();
        PanelCliente = new javax.swing.JPanel();
        textoCliente = new javax.swing.JLabel();
        PanelSalir = new javax.swing.JPanel();
        textoSalir = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textura = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Servicio Asesoramiento");
        setMaximumSize(new java.awt.Dimension(1270, 720));
        setMinimumSize(new java.awt.Dimension(1270, 720));
        setUndecorated(true);
        setResizable(false);

        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Encabezado.setBackground(new java.awt.Color(243, 243, 243));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 52, 52));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Info_32px_1.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(1175, 1175, 1175)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Fondo.add(Encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 60));

        Menu.setBackground(new java.awt.Color(142, 139, 130));
        Menu.setPreferredSize(new java.awt.Dimension(384, 720));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Handle_With_Care_96px.png"))); // NOI18N

        nombreEmpresa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nombreEmpresa.setForeground(new java.awt.Color(233, 220, 190));
        nombreEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreEmpresa.setText("Nombre de la Empresa");

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nombreEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(logo)
                .addGap(18, 18, 18)
                .addComponent(nombreEmpresa)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        Fondo.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 350, 720));

        AreaCentral.setBackground(new java.awt.Color(52, 52, 52));
        AreaCentral.setPreferredSize(new java.awt.Dimension(890, 720));

        PanelEmpleado.setBackground(new java.awt.Color(82, 82, 82));
        PanelEmpleado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelEmpleadoMouseClicked(evt);
            }
        });

        textoEmpleado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textoEmpleado.setForeground(new java.awt.Color(233, 220, 190));
        textoEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Person_32px.png"))); // NOI18N
        textoEmpleado.setText("Empleado");

        javax.swing.GroupLayout PanelEmpleadoLayout = new javax.swing.GroupLayout(PanelEmpleado);
        PanelEmpleado.setLayout(PanelEmpleadoLayout);
        PanelEmpleadoLayout.setHorizontalGroup(
            PanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );
        PanelEmpleadoLayout.setVerticalGroup(
            PanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        PanelCliente.setBackground(new java.awt.Color(82, 82, 82));
        PanelCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelClienteMouseClicked(evt);
            }
        });

        textoCliente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textoCliente.setForeground(new java.awt.Color(233, 220, 190));
        textoCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Person_32px.png"))); // NOI18N
        textoCliente.setText("Cliente");

        javax.swing.GroupLayout PanelClienteLayout = new javax.swing.GroupLayout(PanelCliente);
        PanelCliente.setLayout(PanelClienteLayout);
        PanelClienteLayout.setHorizontalGroup(
            PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );
        PanelClienteLayout.setVerticalGroup(
            PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        PanelSalir.setBackground(new java.awt.Color(82, 82, 82));
        PanelSalir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelSalirMouseClicked(evt);
            }
        });

        textoSalir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textoSalir.setForeground(new java.awt.Color(233, 220, 190));
        textoSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Exit_32px.png"))); // NOI18N
        textoSalir.setText("Salir");

        javax.swing.GroupLayout PanelSalirLayout = new javax.swing.GroupLayout(PanelSalir);
        PanelSalir.setLayout(PanelSalirLayout);
        PanelSalirLayout.setHorizontalGroup(
            PanelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );
        PanelSalirLayout.setVerticalGroup(
            PanelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(233, 220, 190));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menú");

        javax.swing.GroupLayout AreaCentralLayout = new javax.swing.GroupLayout(AreaCentral);
        AreaCentral.setLayout(AreaCentralLayout);
        AreaCentralLayout.setHorizontalGroup(
            AreaCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(AreaCentralLayout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addGroup(AreaCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        AreaCentralLayout.setVerticalGroup(
            AreaCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreaCentralLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel2)
                .addGap(129, 129, 129)
                .addComponent(PanelEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(PanelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(PanelSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        Fondo.add(AreaCentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 720));

        textura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/textura-papel-arrugado.jpg"))); // NOI18N
        Fondo.add(textura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 720));

        getContentPane().add(Fondo, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PanelEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEmpleadoMouseClicked
        setVisible(false);
        new ForListaEmpleados().setVisible(true);
    }//GEN-LAST:event_PanelEmpleadoMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void PanelClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelClienteMouseClicked
        setVisible(false);
        new ForListaClientes().setVisible(true);
    }//GEN-LAST:event_PanelClienteMouseClicked

    private void PanelSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_PanelSalirMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        final String desarrollado = "Aplicacion desarrollada por Jhon Alexander Buitrago\n\n";
        final String foto = "Imagen del menu\nhttp://zonaj.net/imgupload/Papel%20arrugado%20-%20copia_BR18HK.jpg\n\n";
        final String iconos = "Iconos de la aplicación\nhttps://icons8.com/";
        JOptionPane.showMessageDialog(null, desarrollado + foto + iconos, "Información de la aplicación", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AreaCentral;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel PanelCliente;
    private javax.swing.JPanel PanelEmpleado;
    private javax.swing.JPanel PanelSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel nombreEmpresa;
    private javax.swing.JLabel textoCliente;
    private javax.swing.JLabel textoEmpleado;
    private javax.swing.JLabel textoSalir;
    private javax.swing.JLabel textura;
    // End of variables declaration//GEN-END:variables
}
